# Cloudflare Pages / Workers Configuration
name = "sol-peru-front"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_APP_ENV = "production"

# Configuración de Cloudflare Pages Build
[build]
command = "npm run build"
output_directory = ".next"
